[tool.poetry]
name = "курсовая"
version = "0.1.0"
description = ""
authors = ["admin <dimap5825@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
